---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: ProfileName
        pluginConfig:
        - name: "RemovePodsViolatingTopologySpreadConstraint"
          args:
            constraints:
            - ScheduleAnyway
            namespaces:
              include:
              - "te-st"
            labelSelector:
              matchLabels:
                app: nginx
        plugins:
          balance:
            enabled:
              - "RemovePodsViolatingTopologySpreadConstraint"
